version: '3.0'

expectations:
  population_size: 150000

actions:

  generate_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  crMAIN:
    run: stata-mp:latest analysis/cr_analysis_dataset.do
    needs: [generate_cohort]
    outputs:
      moderately_sensitive:
        log: logs/cr_analysis_dataset.log
      highly_sensitive:
        data: output/cr_analysis_dataset.dta

  anSUMM:
    run: stata-mp:latest analysis/an_summary.do
    needs: [crMAIN]
    outputs:
      moderately_sensitive:
        log: logs/an_summary.log
        figure1: output/sgtf_perc_region.svg

  anRISK_TAB1:
    run: stata-mp:latest analysis/an_risk28_table1.do
    needs: [crMAIN]
    outputs:
      moderately_sensitive:
        log: logs/an_risk28_table1.log
        table1text: output/table1_risk28.txt
        table1xlsx: output/table1_risk28.xlsx

  anCOX_TAB1:
    run: stata-mp:latest analysis/an_cox_table1.do
    needs: [crMAIN]
    outputs:
      moderately_sensitive:
        log: logs/an_cox_table1.log
        table1text: output/table1_cox.txt
        table1xlsx: output/table1_cox.xlsx

  anCOX_STAB1:
    run: stata-mp:latest analysis/an_cox_stable1.do
    needs: [crMAIN]
    outputs:
      moderately_sensitive:
        log: logs/an_cox_stable1.log
        table1text: output/stable1_cox.txt
        table1xlsx: output/stable1_cox.xlsx

#  anRISK_MOD:
#    run: stata-mp:latest analysis/an_risk_models.do
#    needs: [crMAIN]
#    outputs:
#      moderately_sensitive:
#        log: logs/an_risk_models.log

  anODDS_MOD:
    run: stata-mp:latest analysis/an_logit_models.do
    needs: [crMAIN]
    outputs:
      moderately_sensitive:
        log: logs/an_logit_models.log
        table1text: output/table3_abs_risk.txt
        table1xlsx: output/table3_abs_risk.xlsx

  anODDS_MOD40:
    run: stata-mp:latest analysis/an_logit_models_40.do
    needs: [crMAIN]
    outputs:
      moderately_sensitive:
        log: logs/an_logit_models_40.log
        table1text: output/table3_abs_risk40.txt
        table1xlsx: output/table3_abs_risk40.xlsx

  anCOX_MOD:
    run: stata-mp:latest analysis/an_cox_models.do
    needs: [crMAIN]
    outputs:
      moderately_sensitive:
        log: logs/an_cox_models.log
        figure1: output/cox_shoen.svg
        figure2: output/cox_km.svg
        figure3: output/cox_cumhaz.svg  
        figure4: output/cox_haz.svg
        table1text: output/table2_hr.txt
        table1xlsx: output/table2_hr.xlsx

  anCOX_SENS:
    run: stata-mp:latest analysis/an_cox_models_sgtf_sens.do
    needs: [crMAIN]
    outputs:
      moderately_sensitive:
        log: logs/an_cox_models_sgtf_sens.log
