version: '3.0'

expectations:
  population_size: 50000

actions:

  generate_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  crMAIN:
    run: stata-mp:latest analysis/cr_analysis_dataset.do
    needs: [generate_cohort]
    outputs:
      moderately_sensitive:
        log: logs/cr_analysis_dataset.log
      highly_sensitive:
        data: output/cr_analysis_dataset.dta

  crNEW:
    run: stata-mp:latest analysis/cr_analysis_new.do
    needs: [generate_cohort]
    outputs:
      moderately_sensitive:
        log: logs/cr_analysis_new.log
      highly_sensitive:
        data: output/cr_analysis_new.dta

  crIMP:
    run: stata-mp:latest analysis/cr_imputed_dataset.do
    needs: [crMAIN]
    outputs:
      moderately_sensitive:
        log: logs/cr_imputed.log
      highly_sensitive:
        data: output/cr_imputed_dataset.dta

  anSUMM:
    run: stata-mp:latest analysis/an_summary.do
    needs: [crNEW]
    outputs:
      moderately_sensitive:
        log: logs/an_summary.log
        #figure1: output/sgtf_perc_region.svg
        #figure2: output/sgtf_perc_region.pdf

  anRISK_TAB1:
    run: stata-mp:latest analysis/an_risk28_table1.do
    needs: [crMAIN]
    outputs:
      moderately_sensitive:
        log: logs/an_risk28_table1.log
        table1text: output/table1_risk28.txt
        table1xlsx: output/table1_risk28.xlsx

  anCOX_TAB1:
    run: stata-mp:latest analysis/an_cox_table1.do
    needs: [crNEW]
    outputs:
      moderately_sensitive:
        log: logs/an_cox_table1.log
        table1text: output/table1_cox.txt
        table1xlsx: output/table1_cox.xlsx
        figure1: output/time_death_hist.svg
        figure2: output/time_date_death_hist.svg
        figure3: output/time_date_death_hist1.svg
        figure4: output/hosp_hist.svg
        figure5: output/hosp_kden.svg
        figure6: output/icu_hist.svg

  anHOSP_TAB1:
    run: stata-mp:latest analysis/an_hosp_table1.do
    needs: [crNEW]
    outputs:
      moderately_sensitive:
        log: logs/an_hosp_table1.log
        table1text: output/table1_hosp.txt
        table1xlsx: output/table1_hosp.xlsx
        figure1: output/time_death_hosp.svg

  anCOX_STAB1:
    run: stata-mp:latest analysis/an_cox_stable1.do
    needs: [crMAIN]
    outputs:
      moderately_sensitive:
        log: logs/an_cox_stable1.log
        table1text: output/stable1_cox.txt
        table1xlsx: output/stable1_cox.xlsx
        table2text: output/stable1_cox_short.txt
        table2xlsx: output/stable1_cox_short.xlsx

#  anRISK_MOD:
#    run: stata-mp:latest analysis/an_risk_models.do
#    needs: [crMAIN]
#    outputs:
#      moderately_sensitive:
#        log: logs/an_risk_models.log

  anODDS_MOD:
    run: stata-mp:latest analysis/an_logit_models.do
    needs: [crMAIN]
    outputs:
      moderately_sensitive:
        log: logs/an_logit_models.log
        table1text: output/table3_abs_risk.txt
        table1xlsx: output/table3_abs_risk.xlsx

  anODDS_MOD40:
    run: stata-mp:latest analysis/an_logit_models_40.do
    needs: [crMAIN]
    outputs:
      moderately_sensitive:
        log: logs/an_logit_models_40.log
        table1text: output/table3_abs_risk40.txt
        table1xlsx: output/table3_abs_risk40.xlsx

  anCOX_MOD:
    run: stata-mp:latest analysis/an_cox_models.do
    needs: [crNEW]
    outputs:
      moderately_sensitive:
        log: logs/an_cox_models.log
        figure1: output/cox_shoen.svg
        figure2: output/cox_km.svg
        figure3: output/cox_cumhaz.svg  
        figure4: output/cox_haz.svg
        table1text: output/table2_hr.txt
        table1xlsx: output/table2_hr.xlsx

  anCOX_HOSP:
    run: stata-mp:latest analysis/an_cox_hosp.do
    needs: [crNEW]
    outputs:
      moderately_sensitive:
        log: logs/an_cox_hosp.log
        figure1: output/cox_shoen_hosp.svg
        #figure2: output/cox_km.svg
        #figure3: output/cox_cumhaz.svg  
        figure2: output/cox_haz_hosp.svg
        table1text: output/table2_hr_hosp.txt
        table1xlsx: output/table2_hr_hosp.xlsx

  anCOX_DHOSP:
    run: stata-mp:latest analysis/an_cox_deathhosp.do
    needs: [crNEW]
    outputs:
      moderately_sensitive:
        log: logs/an_cox_deathhosp.log
        figure1: output/cox_shoen_deathhosp.svg
        #figure2: output/cox_km.svg
        #figure3: output/cox_cumhaz.svg  
        figure2: output/cox_haz_deathhosp.svg
        table1text: output/table2_hr_deathhosp.txt
        table1xlsx: output/table2_hr_deathhosp.xlsx

  anCOX_SENS:
    run: stata-mp:latest analysis/an_cox_models_sgtf_sens.do
    needs: [crMAIN]
    outputs:
      moderately_sensitive:
        log: logs/an_cox_models_sgtf_sens.log

  anCOX_IMP:
    run: stata-mp:latest analysis/an_cox_imputed.do
    needs: [crIMP]
    outputs:
      moderately_sensitive:
        log: logs/an_cox_imputed.log
      highly_sensitive:
        data2: output/an_imputed_eth2.ster